<a href="https://colab.research.google.com/github/rajashekarkasturi/ML-hands-on/blob/master/Part_1_tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
x = tf.constant([[1,2,3],
                 [4,5,6]])

print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
<dtype: 'int32'>


In [ ]:
print(x+x)
print(x*3)

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 3  6  9]
 [12 15 18]], shape=(2, 3), dtype=int32)


In [ ]:
print(x)
x@ tf.transpose(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [ ]:
tf.concat([x,x,x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
x = tf.cast(x, dtype=tf.float64)
print(x)
print(x.shape)

print("reduced sum")
print(tf.reduce_sum(x,axis=-1))

print()
x = tf.concat(x, axis=-1)

tf.nn.softmax(x, axis=-1)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
(2, 3)
reduced sum
tf.Tensor([ 6. 15.], shape=(2,), dtype=float64)



<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])>

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float64, numpy=21.0>

In [ ]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


In [ ]:
new_var = tf.Variable(["hello"])