<a href="https://colab.research.google.com/github/rajashekarkasturi/ML-hands-on/blob/master/Part_2_tf_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
scalar = tf.constant(6)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
# Number of dimensions
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix

matrix2 = tf.constant([[19., 5.],
                       [3., 2.],
                       [8.,9.]], dtype=tf.float16)  #specifying with data type parameter
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[19.,  5.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
#creating a tensor
tensor = tf.constant([ [[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                         [10,11,12]]
                      ])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

TF.Variable

In [ ]:
mutable_tensor =tf.Variable([10,8])
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [ ]:
mutable_tensor[0].assign(7)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 8], dtype=int32)>

Creating Random Tensors

In [ ]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random3 = tf.constant( [[4,5],
                       [1,3],
                      [2,6]])
random3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 3],
       [2, 6]], dtype=int32)>

In [ ]:
tf.random.shuffle(random3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 6],
       [1, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tf.random.set_seed= 32  #global seed
tf.random.shuffle(random3, seed = 32) #operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [2, 6],
       [1, 3]], dtype=int32)>

Other ways to creating a tensor

In [ ]:
tf.zeros(shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

#Converting numpy arrays intro tensors

The main difference is tensorflow tensors can be run on GPU

In [ ]:
import numpy as np
#generally capital variables for tensors
#lower case for vectors

In [ ]:
A = np.array([1,2,3,4])
A

array([1, 2, 3, 4])

In [ ]:
new_A = tf.constant(A)
new_A

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

##Getting information from tensors


*   Shape
*   Rank
*   Axis
*   Dimension

In [ ]:
rank_4_tensor = tf.ones(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get attributes from tensors

print("Data type of every element: ", rank_4_tensor.dtype)
print("Number of dimensions(rank): ", rank_4_tensor.ndim)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])

Data type of every element:  <dtype: 'float32'>
Number of dimensions(rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2


Extending dimensions

In [ ]:
rank2_tensor = tf.random.Generator.from_seed(42)
rank2_tensor = rank2_tensor.normal(shape=(2,2))
#Created a rank2 tensor
rank2_tensor.numpy()

#extending the dimension of it method =1
rank3_tensor = rank2_tensor[...,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

In [ ]:
#extending the dimensions method-2
tf.expand_dims(rank2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702]],

       [[ 0.07595026],
        [-1.2573844 ]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ]]], dtype=float32)>

##Tensor Manipulation

In [ ]:
tensor1 = tf.constant([[4,1],[5,3]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 1],
       [5, 3]], dtype=int32)>

In [ ]:
tensor1*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 10],
       [50, 30]], dtype=int32)>

#Matrix multiplication with tensors


In [ ]:
print (tensor1)
tf.matmul(tensor1,tensor1)

tf.Tensor(
[[4 1]
 [5 3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[21,  7],
       [35, 14]], dtype=int32)>

In [ ]:
tensor2 =tf.constant( [[1,2,5],
                     [7,2,1],
                     [3,3,3] ])
tensor3 = tf.constant( [ [3, 5],
                       [6,7],
                       [1,8]])

In [ ]:
tf.matmul(tensor2, tensor3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

Changing the data type of tensors

In [ ]:
import tensorflow as tf
chgtype1 = tf.constant([1.5, 1.8])
print(chgtype1)

tf.Tensor([1.5 1.8], shape=(2,), dtype=float32)


In [ ]:
chgtyp16 = tf.cast(chgtype1, dtype="float16")
print(chgtyp16)

tf.Tensor([1.5 1.8], shape=(2,), dtype=float16)


**Aggregating Tensors**

Condensing them from multiple values down to small amount of values


In [ ]:
import tensorflow as tf
#Getting the abosolute values
D =tf.constant([-55,-4])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([55,  4], dtype=int32)>

**populating the abs**
* min
* max
* mean
* sum


In [ ]:
import numpy as np
E =tf.constant(np.random.randint(0,100,size=50))
E
tf.size(E), E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1)

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
#Mean of the tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
#Finding the variance and standard deviation of the E occurs on dtype=real and complex
tf.math.reduce_variance(tf.cast(E, dtype="float32"))

<tf.Tensor: shape=(), dtype=float32, numpy=969.70447>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype="float32"))

<tf.Tensor: shape=(), dtype=float32, numpy=31.140078>

In [ ]:
#Finding the postional maximum and minimum

#Creating a matrix

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Postional max -> arg_max -> gives the position
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index of our arg_max
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the positional min
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**Squeezing our tensors**

In [ ]:
###Squeezing our tensors
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [ ]:
squeezed_tensor = tf.squeeze(G)
squeezed_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

**One Hot Encoding**

In [ ]:
code = [0, 1, 2, 3, 4]
one_hot_encode = tf.one_hot(code, depth = 5)
one_hot_encode

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specifying custom values for one_hot_encode

one_hot_encode_custom = tf.one_hot(code , depth = 5, on_value="true", off_value="false")
one_hot_encode_custom

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'true', b'false', b'false', b'false', b'false'],
       [b'false', b'true', b'false', b'false', b'false'],
       [b'false', b'false', b'true', b'false', b'false'],
       [b'false', b'false', b'false', b'true', b'false'],
       [b'false', b'false', b'false', b'false', b'true']], dtype=object)>

**Square, log and square Root**

In [ ]:
H = tf.range(0,10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H, dtype="float32"))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ,
       2.236068  , 2.4494896 , 2.6457512 , 2.828427  , 3.        ],
      dtype=float32)>

#Make our Tensors run on GPU

In [ ]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Feb  9 16:23:27 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8    26W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------